### ISSUE TITLE
GPIO configuration from the web UI interface

### ISSUE THREAD

**Issue by PetrJakes** [steadramon/ESPGeiger#1]
It would be great if there is a possibility to set up the GPIO pin(s) for input impulses and for output impulses (testing mode) in teh web UI interface.

**Comment by steadramon** [comment]
Hi there, this is something I have considered, especially since building is now automatic through github.

**Comment by PetrJakes** [comment]
Tasmota firmware has it for long time and I found it very useful.

**Comment by krotoniec** [comment]
Definitely GPIO config would be something very useful.

**Comment by realatomisator** [comment]
Thank you very much for this great project. Unfortunately I have Problems with an 38 PIN ESP32 and a cajoe v1.1. 
A GPIO config in the Setup would be helpful.
Thanks a lot!

**Comment by steadramon** [comment]
The latest pushes to main has this ability. I will test further and look to make a release

**Comment by realatomisator** [comment]
Thank you very much. With the new 0.39 release it works fine!!!
