### ISSUE TITLE
The time shown in the chart is a different timezone to the log window time.

### ISSUE THREAD

**Issue by Mr-Blinky** [steadramon/ESPGeiger#12]
When viewing the status page the time that is shown in the CPM chart is a different timezone to the time shown in the log window.

I suspect the chart time is using my local timezone (currently BST) and the log time is UTC. 

Please see attached screen grab.

Thanks

![ESPGeiger-4e4aee - timezone issue](https://github.com/user-attachments/assets/d577f7b0-966e-47e3-8643-2b58a5fcfae4)

**Comment by steadramon** [comment]
Hi - the chart is drawn in browser and uses the Javascript Date object - displaying the time when the current value was polled. Javascript's date object has few facilities for working with time in other time zones.

The log is internal to the ESP device and so the time output is dated to the timezone as defined on the ESP.

The discrepency you're seeing is as you pointed out - the timezone of your browser and the ESPGeiger are different.

**Comment by steadramon** [comment]
Fix for mismatching timezones between ESPGeiger and local browser logging is in the pipeline.
