### ISSUE TITLE
Cajoe image not working

### ISSUE THREAD

**Issue by shyrwall** [steadramon/ESPGeiger#13]
Just got a cajoe esp32-gc board and the image v0.6.1 is not working in PCNT. However NO_PCNT is working. 

Since I never used espgeiger before I don't know if it worked in releases before 0.6.1

**Comment by steadramon** [comment]
Hi there - thanks for the report. I had a similar query several months ago - I thought the issue had been resolved, this could be related to the Pin mode set after the PCNT is initialised.

I don't have a Cajoe ESP32 to test with, but I do have something we can try before relegating the Cajoe build to NO_PCNT.

Can you try the latest esp32_cajoe_iotgm_test_pcnt build from the pipeline, please?

https://github.com/steadramon/ESPGeiger/actions/runs/10430810811/artifacts/1822671082

Thanks!

**Comment by shyrwall** [comment]
Works.

Did the upgrade with firmware.bin via the webinterface. Version after came up as devel/0558524

Thanks

**Comment by steadramon** [comment]
That's great news - thank you for testing - I'll get this out in an official release soon - but this is exactly the same as 0.6.1 except with this fix.

If possible, would you be willing to take a photo or two of the Cajoe device running the ESPGeiger firmware? I'd really like to use these for the documentation page

You should be able to upload them here if you're able,

Thanks!

Paul

**Comment by shyrwall** [comment]
![20240818_054146](https://github.com/user-attachments/assets/5e270d29-b9fc-4dc3-91c2-c96f57752d4f)

**Comment by steadramon** [comment]
Release [v0.6.2](https://github.com/steadramon/ESPGeiger/releases/tag/v0.6.2) has these specific fixes for the Cajoe ESP32-GC image
