### ISSUE TITLE
SSD1306 Display not working ESPGeiger v0.6.2 with Pulse over Chrome Firmware

### ISSUE THREAD

**Issue by raindancer2204** [steadramon/ESPGeiger#15]
Hello,
i wired my ESP as follows and then installed the current firmware "Pulse" ESPGeiger v0.6.2 via Chrome, with the check mark next to "I have a SD1306 OLED screen connected". I then entered the WiFi data and can connect properly. I want to connect an " Cajoe Geiger Counter."

Where can I activate the display please? The wiring should be fine. 

![image](https://github.com/user-attachments/assets/c18e4a37-97f7-4fc2-9c7c-6efa4eb1ccb3)

Can someone please check this?

Thank you

**Comment by steadramon** [comment]
I think this is to do with the pins assigned in ESPGeiger. 

Can you try with the SCL/SDA connections between the D1 mini and OLED display flipped? I think this is something I should fix for the standard builds.

**Comment by raindancer2204** [comment]
I turned the 2 PINS and the display turned on. It would be great if you could implement this for the “standard web builds”. Then I could test it again with the “default cabling”.

Are you planning to support a larger display like the "SH1106" via WEB Firmware in the near future?

Can you add the readme under instructions? Category "2. Connect hardware"

Thanks for the quick reply.

**Comment by steadramon** [comment]
> Are you planning to support a larger display like the "SH1106" via WEB Firmware in the near future?

Not in the near future - I do not have access to one of these displays at present. However I'd be happy to look at any PRs that came for this. Some thought around implementation and supporting the different builds would be needed.

I'll add some more information regarding SSD1306 setup on the readme and documentation.
