### ISSUE TITLE
OLED display not working

### ISSUE THREAD

**Issue by alestanga** [steadramon/ESPGeiger#3]
hi, I've just installed ESPGeiger on my ESP8266 connected to a J305B tube.
I can't get the OLED display to work.
It worked perfectly with my old sketch, using the address 0x3c (it seems to me that you're using this very same address in your config file).
do you have any suggestion?
my sketch uses this command to initialize the display:
display.begin(SSD1306_SWITCHCAPVCC, 0x3c)
thank you.

**Comment by steadramon** [comment]
>  display.begin(SSD1306_SWITCHCAPVCC, 0x3c)

This seems to be for the Adafruit GFX library, which isn't in use in ESPGeiger - here SSD1306Wire ("thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays" is used - can you clarify this is what you used in your previous sketch?

I've tested with a number of different SSD1306 devices and all seemed fine - can you confirm it is a 128x64 screen? Do you get any feedback at all? Have you tried swapping the SDA/SCK pins?

**Comment by alestanga** [comment]
yes, my previous sketch used this library: https://github.com/adafruit/Adafruit_SSD1306
I have to try with your driver, maybe tonight or tomorrow.
I haven't tried to swap SDA/SCK because it worked right until I've flashed it with your web flasher.
yes, the display is 128x64 0.96"

**Comment by alestanga** [comment]
i've tried to upload to the same board the ssd1306_128x64_i2c example found in the Adafruit SSD1306 library and it works just fine, after changing the address from 0x3d to 0x3c (it says that the first one is for the 128x64 and the latter for the 128x32 but mine is 128x64 and is on the 0x3c address)
so SDA SCL (i'm using the i2c protocol not the SPI) are connected properly.

**Comment by steadramon** [comment]
That's very odd! 

Is this built yourself within platformio or via install.espgeiger.com ?

**Comment by alestanga** [comment]
I’ve installed it via the web installer. 
I’ve also updated it with the 8266 oled pulse firmware bin file, just to be sure, but to no avail. 

Inviato da iPad

**Comment by steadramon** [comment]
That's very strange. I've just installed on a previously unused ESP8266 and SD1306 and it's working fine for me.
Using install.espgeiger.com - ESP8266, 0.3.0 Pulse with OLED ticked

D1 -> SDA
D2 -> SCL

I really cannot explain this if this matches your setup...

**Comment by alestanga** [comment]
Ok. I’m sorry I haven’t tried early. 
I’ve swapped SDA and SCL and now it works. 
Mine were reversed: 1 SCL, 2 SDA. 
But it worked just fine as it was with every other sketch. 

Inviato da iPad

**Comment by steadramon** [comment]
This might be more my choice of pins - rather than the default I have them swapped - this is partly for my hardware layout, but I am now considering that choice..

**Comment by alestanga** [comment]
Well. Not a big deal. 
I only had to swap them. 
Thank you for your support. 
That’s not related but could it be that if you set a wrong ratio the first time you set up the application then the gmc uploader uses the wrong value even after you’ve change it?

Inviato da iPad

**Comment by steadramon** [comment]
I noticed this recently, a new release soon will fix this properly
