### ISSUE TITLE
Disable all output except Serial

### ISSUE THREAD

**Issue by pauldupuyjr** [steadramon/ESPGeiger#5]
What's the best way to disable all output other than Serial? I see a SERIALOUT flag but nothing for disabling MQTT, Thingspeak, etc.

**Comment by steadramon** [comment]
By default nothing sends unless configured, but the items are still built - using memory etc....

In honesty I should look at cleaning up the build options to enable/disable these features - it would also aid in my debugging/memory tracking at the moment.

**Comment by pauldupuyjr** [comment]
Got it. Thanks for the quick reply. Cheers,

**Comment by pauldupuyjr** [comment]
Got it. Thanks for the quick reply. Cheers,
